apiVersion: v1
kind: Service
metadata:
  name: crazy-api-service
  namespace: development
spec:
  type: NodePort
  selector:
    type: web-api
  ports:
    - protocol: TCP
      targetPort: 80
      port: 5000
      nodePort: 30002  